### ISSUE TITLE
Epic: Refactoring of the XOAI library

### ISSUE THREAD

**Issue by poikilotherm** [gdcc/xoai#1]
- [x] Remove Log4J usage and any dependencies using it
- [x] Use ~~System.Logger~~ SLF4J for logging
- [ ] Add docs on how to set log levels from using applications
- [x] Switch all tests to JUnit5
- [x] Switch all `java.util` time classes to `java.time` classes
- [x] Try to get rid of `com.lyncode.xml`
- [x] Use modern Java XML Binding and writing
- [x] Update Hamcrest (replace?)
- [x] Switch all packages from `org.dspace` to `io.gdcc`
- [x] Remove Apache HTTP client and use JVM native (makes the lib JDK11+)
- [x] Use Java 8/11 constructs like autoclosables, streams etc
- [ ] Provide interfaces used as XOAI extension points for application with default methods (e. g. for data-provider sets interfaces)
- [ ] Double-check every module for reading back data from a stream that might not contain data due to a writer buffer (this caused trouble that appeared as failing tests)

**Comment by poikilotherm** [comment]
Started in https://github.com/gdcc/xoai/tree/branch-5.0
